export const data =[
    {
        "id": 1,
        "name": "Face Mask",
        "category": "Grape Fruit",
        "price" : "$16,00",
        "image": "item-2.png",
        "quantity": 4,
        "accessories" : [
            {
                "id":1,
                "name" : "Comb 2.0",
                "category" : "Original Version",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
            {
                "id":2,
                "name" : "Watch+",
                "category" : "Trending 2020",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
            {
                "id":3,
                "name" : "Camera",
                "category" : "Classic 1992",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
        ],
    },
    {
        "id":2,
        "name": "Rice Cream",
        "category": "Rice Bran Oil",
        "price" : "$19,00",
        "image": "item-2.png",
        "quantity": 4,
        "accessories" : [
            {
                "id":1,
                "name" : "Comb 2.0 - Item 2",
                "category" : "Original Version",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
            {
                "id":2,
                "name" : "Watch+ Item 2",
                "category" : "Trending 2020",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
            {
                "id":3,
                "name" : "Camera Item 2",
                "category" : "Classic 1992",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
            // {
            //     "id":4,
            //     "name" : "Wrist Band Item 2",
            //     "category" : "Classic 1992",
            //     "price" : "$19,00",
            //     "image" : "accessories-1.png",
            // },
        ],
    },
    {
        "id":3,
        "name": "Aromatic Water",
        "category": "Grape Fruit",
        "price" : "$16,00",
        "image": "item-2.png",
        "quantity": 4,
        "accessories" : [
            {
                "id":1,
                "name" : "Comb 2.0 - Item 3",
                "category" : "Original Version",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
            {
                "id":2,
                "name" : "Watch+ Item 3",
                "category" : "Trending 2020",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
            {
                "id":3,
                "name" : "Camera Item 3",
                "category" : "Classic 1992",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
        ],
    },
    {
        "id":4,
        "name": "Lemon Cream",
        "category": "Bran Oil",
        "price" : "$19,00",
        "image": "item-2.png",
        "quantity": 4,
        "accessories" : [
            {
                "id":1,
                "name" : "Comb 2.0 - Item 4",
                "category" : "Original Version",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
            {
                "id":2,
                "name" : "Watch+ Item 4",
                "category" : "Trending 2020",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
            {
                "id":3,
                "name" : "Camera Item 4",
                "category" : "Classic 1992",
                "price" : "$19,00",
                "image" : "accessories-1.png",
            },
            // {
            //     "id":4,
            //     "name" : "Socks Item 4",
            //     "category" : "Classic 1992",
            //     "price" : "$19,00",
            //     "image" : "accessories-1.png",
            // },
        ],
    },
];